image:
  file: .gitpod.Dockerfile

tasks:
  - command: gp url 3000 >> ui/src/assets/api.config.txt
  - command: cd ui; NG_CLI_ANALYTICS=ci npm install; npx ng serve --disableHostCheck
  - command: cd api; NG_CLI_ANALYTICS=cis npm install; npm run start
  - command: mkdir -p /workspace/data && mongod --dbpath /workspace/data